# Generated by Django 4.2.5 on 2023-10-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listings_comments_bids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
