# Generated by Django 4.2.5 on 2023-10-13 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_listings_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bids",
            new_name="Bid",
        ),
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.RenameModel(
            old_name="Listings",
            new_name="Listing",
        ),
    ]
