# Generated by Django 4.2.5 on 2023-10-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_price_listing_starting_bid_alter_bid_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.TextField(default="description"),
            preserve_default=False,
        ),
    ]
