# Generated by Django 4.2.5 on 2023-10-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_listing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_price",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
