# Generated by Django 4.2.5 on 2023-10-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_listing_current_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[("a", "A"), ("b", "B"), ("c", "C")],
                default="a",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
