# Generated by Django 4.2.5 on 2023-10-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_listing_active_alter_bid_user_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        choices=[
                            ("art", "Art"),
                            ("elec", "Electronics"),
                            ("book_mov_mus", "Books, movies & music"),
                            ("home", "Home & Garden"),
                            ("clothes", "Clothes, shoes & accessoires"),
                            ("sport", "Sporting goods"),
                            ("baby", "Baby essentials"),
                            ("pet", "Pet essentials"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_category_items",
                        to="auctions.listing",
                    ),
                ),
            ],
        ),
    ]
