# Generated by Django 4.2.5 on 2023-12-04 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(
                choices=[
                    ("art", "Art"),
                    ("elec", "Electronics"),
                    ("book_mov_mus", "Books, movies & music"),
                    ("home", "Home & Garden"),
                    ("clothes", "Clothes, shoes & accessoires"),
                    ("sport", "Sporting goods"),
                    ("baby", "Baby essentials"),
                    ("pet", "Pet essentials"),
                    ("other", "Other"),
                    ("cars", "Cars"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
