# Generated by Django 4.2.5 on 2023-12-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_comment_time_alter_category_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="number_of_bids",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
