# Generated by Django 4.2.5 on 2023-12-20 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_listing_number_of_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
